### ISSUE TITLE
This driver looks like you could submit it to mainline

### ISSUE THREAD

**Issue by SamPovilus** [jyelloz/tlc5940-linux#1]
I didn't spend too long looking at it but it seems like you might be able to throw it into mainline https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html is there a reason you didn't? I hate to see code like this languish outside the kernel.

**Comment by jyelloz** [comment]
This driver is only good as a toy or for demo purposes. The timer task isn't guaranteed to be executed on time in standard Linux and the TLC5940 requires that it is. Nobody should use this for production purposes.
